Shop/Shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

from orders.views import stripe_webhook_view

urlpatterns = [
				  path('admin/', admin.site.urls),
				  path('', include("products.urls")),
				  path('user/', include("users.urls", namespace='users')),
				  path('order/', include("orders.urls", namespace='order')),
				  path('accounts/', include('allauth.urls')),
				  path('webhook/', stripe_webhook_view, name='stripe_webhook_view'),
				  path('api/', include("api.urls", namespace='api')),
				  path('api-token-auth/', views.obtain_auth_token),
			  ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/api/urls.py
from django.urls import include, path
from rest_framework import routers

from .views import BasketModelViewSet, ProductModelViewSet

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'products',ProductModelViewSet)
router.register(r'baskets',BasketModelViewSet)

urlpatterns = [
	path('', include(router.urls)),
]

Shop/orders/urls.py
from django.urls import path

from .views import *

app_name = 'orders'
urlpatterns = [path('create/', OrderCreateView.as_view(), name='create'),
			   path('success/', SuccessTemplateView.as_view(), name='success'),
			   path('cancel/', CancelTemplateView.as_view(), name='cancel'),
			   path('', OrderListView.as_view(), name='order_list'),
			   path('order/<int:pk>', OrderDetailView.as_view(), name='order_info'),
			   ]

Shop/orders/models.py
from django.db import models

from products.models.basket.models import Basket
from users.models.users.models import User

# Create your models here.

class Order(models.Model):
	CREATED = 0
	PAID = 1
	ON_WAY = 2
	DELIVERED = 3
	STATUSES = (
		(CREATED,"Создан"),
		(PAID,"Оплачен"),
		(ON_WAY,"В пути"),
		(DELIVERED,"Доставлен"),
	)

	fio = models.CharField(max_length=128)
	email = models.EmailField(max_length=128)
	addres = models.CharField(max_length=128)
	city = models.CharField(max_length=128)
	country = models.CharField(max_length=128)
	zip_code = models.CharField(max_length=128)
	basket_hitstory = models.JSONField(default=dict)
	created = models.DateTimeField(auto_now_add=True)
	status = models.PositiveSmallIntegerField(default=CREATED,choices=STATUSES)
	initiator = models.ForeignKey(to=User,on_delete=models.CASCADE)

	def __str__(self):
		return f'{self.id}'

	def update_after_payment(self):
		baskets = Basket.objects.filter(user=self.initiator)
		self.status = self.PAID
		self.basket_hitstory = {
			'purchased_items': [basket.de_json() for basket in baskets],
			'total_sum': float(baskets.total_sum()),
		}
		baskets.delete()
		self.save()

Shop/orders/forms.py
from django import forms

from orders.models import Order


class OrederForm(forms.ModelForm):
	fio = forms.CharField(widget=forms.TextInput(attrs={
		'name': 'firstname', 'placeholder': 'Имя Фамилия Отчество'}))
	email = forms.CharField(widget=forms.TextInput(attrs={
		'name':'email','placeholder':'example@email.ru'}))
	addres = forms.CharField(widget=forms.TextInput(attrs={
		'name':'address','placeholder':'Томская 44-39'}))
	city = forms.CharField(widget=forms.TextInput(attrs={
		'name':'city','placeholder':'Москва'}))
	country = forms.CharField(widget=forms.TextInput(attrs={
		'name':'state','placeholder':'Россия'}))
	zip_code = forms.CharField(widget=forms.TextInput(attrs={
		'name':'zip','placeholder':'10001'}))
	class Meta:
		model = Order
		fields = ('fio', 'email', 'addres', 'city', 'country', 'zip_code')

Shop/orders/views.py
from http import HTTPStatus

import stripe
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from common.views import TitleMixin
from orders.forms import OrederForm
from orders.models import Order
from orders.services.order.create import OrderCreateServices
from orders.services.order_list.queryset import OrderQuerysetService

stripe.api_key = settings.STRIPE_SECRET_KEY


class SuccessTemplateView(TitleMixin, TemplateView):
	template_name = 'orders/order_success.html'
	title = "Спасибо за заказ"


class CancelTemplateView(TitleMixin, TemplateView):
	template_name = 'orders/order_cancel.html'
	title = "Заказ отменен"


class OrderDetailView(DetailView):
	template_name = 'orders/order_detail.html'
	model = Order


class OrderListView(TitleMixin, ListView):
	template_name = 'orders/orders.html'
	title = "История заказов"
	ordering = ('-id')

	def get_queryset(self):
		outcome = OrderQuerysetService.execute({'user': self.request.user})
		return outcome


class OrderCreateView(TitleMixin, CreateView):
	template_name = 'orders/order_create.html'
	form_class = OrederForm
	success_url = reverse_lazy('orders:create')
	title = 'Оформление заказа'

	def post(self, request, *args, **kwargs):
		super(OrderCreateView, self).post(request, *args, **kwargs)
		outcome = OrderCreateServices.execute({'user': self.request.user, 'order': self.object.id})
		return HttpResponseRedirect(outcome.url, status=HTTPStatus.SEE_OTHER)

	def form_valid(self, form):
		form.instance.initiator = self.request.user
		return super(OrderCreateView, self).form_valid(form)


@csrf_exempt
def stripe_webhook_view(request):
	payload = request.body
	sig_header = request.META['HTTP_STRIPE_SIGNATURE']
	event = None

	try:
		event = stripe.Webhook.construct_event(
			payload, sig_header, settings.STRIPE_WEBHOOK
		)
	except ValueError:
		# Invalid payload
		return HttpResponse(status=400)
	except stripe.error.SignatureVerificationError:
		# Invalid signature
		return HttpResponse(status=400)

	# Handle the checkout.session.completed event
	if event['type'] == 'checkout.session.completed':
		session = event['data']['object']

		# Fulfill the purchase...
		fulfill_order(session)

	# Passed signature verification
	return HttpResponse(status=200)


def fulfill_order(session):
	order_id = int(session.metadata.order_id)
	order = Order.objects.get(id=order_id)
	order.update_after_payment()

Shop/orders/templates/orders/order_cancel.html
{% extends "products/base.html" %}
{% load static %}
{% block content %}
<link rel='stylesheet' href='{% static "products/css/style.css" %}'>
<div class="container">
    <input type="checkbox" id="check">
    <div class="login form">
        <header>Оплата заказа</header>
        <center><h3>Оплата не прошла, заказ отменен</h3></center>
        <h2>
            <center><a href="{% url 'orders:order_list' %}">Перейти в заказы</a></center>
        </h2>
    </div>
</div>
{% endblock %}

Shop/orders/templates/orders/order_create.html
{% extends "products/base.html" %}
{% block content %}
{% load static %}
<link rel='stylesheet' href='{% static "products/css/style_order_create.css" %}'>
{% if user.is_verified_email %}
<div class="row">
    <div class="col-75">
        <div class="container">
            <form action="{% url 'orders:create' %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-50">
                        <h3>
                            <center>Оформление заказа</center>
                        </h3>
                        <label for="{{ form.fio.id_for_labe }}"><i class="fa fa-user"></i>ФИО</label>
                        {{ form.fio }}
                        <label for="{{ form.email.id_for_labe }}"><i class="fa fa-envelope"></i> Email</label>
                        {{ form.email }}
                        <label for="{{ form.addres.id_for_labe }}"><i class="fa fa-address-card-o"></i>Адрес</label>
                        {{ form.addres }}
                        <label for="{{ form.city.id_for_labe }}"><i class="fa fa-institution"></i>Город</label>
                        {{ form.city }}
                        <div class="row">
                            <div class="col-50">
                                <label for="{{ form.country.id_for_labe }}">Страна</label>
                                {{ form.country }}
                            </div>
                            <div class="col-50">
                                <label for="{{ form.zip_code.id_for_labe }}">Индекс</label>
                                {{ form.zip_code }}
                            </div>
                        </div>
                    </div>


                </div>
                <input type="submit" value="Продолжить оформление заказа" class="btn">
            </form>
        </div>
    </div>

    <div class="col-25">
        <div class="container">
            <h4>
                <center>Корзина</center>
            </h4>
            {% for basket in baskets %}
            <p><a href="{% url 'products' basket.product.id %}">{{ basket.product.name }}</a> <span class="price">{{ basket.product.price }} Руб.</span>
            </p>
            <small class="text-muted">{{ basket.quantity }} шт.</small>
            {% endfor %}
            <hr>
            <p>Всего <span class="price" style="color:black"><b>{{ baskets.total_sum }} Руб.</b></span></p>
        </div>
    </div>
</div>
{% else %}

<h1><center>Для совершения покупок необходимо потдвердить свой аккаунт через email</center></h1>

{% endif %}
{% endblock %}

Shop/orders/templates/orders/order_detail.html
{% extends "products/base.html" %}
{% block title %} Заказ № {{object.id}} {% endblock %}
{% block content %}


<center>
    <div class="container">
        <h2 class="mt-5 mb-4">Ваш заказ номер {{object.id}}</h2>
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Название</th>
                    <th>Кол-во</th>
                    <th>Цена</th>
                    <th>Сумма</th>
                </tr>
                </thead>
                <tbody>
                {% for purchased_item in object.basket_hitstory.purchased_items %}
                <tr>
                    <td>{{purchased_item.product_name}}</td>
                    <td> {{purchased_item.quantity}}</td>
                    <td> {{purchased_item.price}}</td>
                    <td> {{purchased_item.sum}} Руб.</td>
                    <td>

                    </td>
                    {% endfor %}
                </tr>
                </tbody>
            </table>
            <h4>Итог - {{ object.basket_hitstory.total_sum }} Руб.</h4>
        </div>
    </div>
</center>

{% endblock %}

Shop/orders/templates/orders/order_success.html
{% extends "products/base.html" %}
{% load static %}
{% block content %}
<link rel='stylesheet' href='{% static "products/css/style.css" %}'>
<div class="container">
    <input type="checkbox" id="check">
    <div class="login form">
        <header>Оплата заказа</header>
       <center><h3>Поздравляем, Вы успешно оплатили товар!</h3></center>
        <h2><center><a href="{% url 'orders:order_list' %}">Перейти в заказы</a></center></h2>
    </div>
</div>
{% endblock %}

Shop/orders/templates/orders/orders.html
{% extends 'products/base.html' %}
{% block content %}
{% load humanize %}

<center>
<div class="container">
  <h2 class="mt-5 mb-4">История заказов</h2>
  {% if object_list %}
  <div class="table-responsive">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Номер заказа</th>
          <th>Дата заказа</th>
          <th>Статус</th>
          <th>Сумма заказа</th>
        </tr>
      </thead>
      <tbody>
      {% for order in object_list %}
        <tr>
          <td>{{order.id}}</td>
          <td>{{order.created|naturaltime}}</td>
          <td>{{order.get_status_display}}</td>
          <td>{{order.basket_hitstory.total_sum}} Руб.</td>
          <td>

            <a href="{% url 'orders:order_info' order.id %}" class="btn btn-primary btn-sm">Просмотреть детали</a>
          </td>
          {% endfor %}
        </tr>
      </tbody>
    </table>
  </div>
  {% else %}
  <h4>История заказов пуста</h4>
  {% endif %}
</div>
</center>
{% endblock %}