Shop/Shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

from orders.views import stripe_webhook_view

urlpatterns = [
				  path('admin/', admin.site.urls),
				  path('', include("products.urls")),
				  path('user/', include("users.urls", namespace='users')),
				  path('order/', include("orders.urls", namespace='order')),
				  path('accounts/', include('allauth.urls')),
				  path('webhook/', stripe_webhook_view, name='stripe_webhook_view'),
				  path('api/', include("api.urls", namespace='api')),
				  path('api-token-auth/', views.obtain_auth_token),
			  ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/api/urls.py
from django.urls import include, path
from rest_framework import routers

from .views import BasketModelViewSet, ProductModelViewSet

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'products',ProductModelViewSet)
router.register(r'baskets',BasketModelViewSet)

urlpatterns = [
	path('', include(router.urls)),
]

Shop/orders/urls.py
from django.urls import path

from .views import *

app_name = 'orders'
urlpatterns = [path('create/', OrderCreateView.as_view(), name='create'),
			   path('success/', SuccessTemplateView.as_view(), name='success'),
			   path('cancel/', CancelTemplateView.as_view(), name='cancel'),
			   path('', OrderListView.as_view(), name='order_list'),
			   path('order/<int:pk>', OrderDetailView.as_view(), name='order_info'),
			   ]

Shop/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import *

app_name = 'users'
urlpatterns = [
	path('login/', UserLoginView.as_view(), name='login'),
	path('register/', UserRegistrationView.as_view(), name='register'),
	path('profile/<int:pk>/', UserProfileView.as_view(), name='profile'),
	path('logout/', LogoutView.as_view(), name='logout'),
	path('truereg/', SuccessfulRegistrationView.as_view(), name='truereg'),
	path('verify/<str:email>/<uuid:code>/', EmailVerifactionView.as_view(), name='verification'),
]

Shop/users/models/comments/models.py
from django.db import models

from products.models.basemodel.models import BaseModel
from products.models.product.models import Product
from users.models.users.models import User


class Comment(BaseModel, models.Model):
	text = models.TextField()
	product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
	user = models.ForeignKey(to=User, on_delete=models.CASCADE)

	def __str__(self):
		return self.text

	class Meta:
		app_label = 'users'

Shop/users/models/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

from products.models.basemodel.models import BaseModel


class User(AbstractUser,BaseModel):
	phone = PhoneNumberField(null=True, blank=True)
	img = models.ImageField(upload_to='users/%Y/%m/%d/', null=True, blank=True)
	is_verified_email = models.BooleanField(default=False)
	email = models.EmailField(unique=True, null=True, blank=True)

Shop/users/models/usersemailverifications/models.py
from datetime import timedelta

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils.timezone import now
from phonenumber_field.modelfields import PhoneNumberField

from users.models.users.models import User


class EmailVerification(models.Model):
	code = models.UUIDField(unique=True)
	user = models.ForeignKey(to=User, on_delete=models.CASCADE)
	created = models.DateTimeField(auto_now_add=True)
	expiration = models.DateTimeField()

	def __str__(self):
		return f'EmailVerification object {self.user.email}'

	def send_verifaction_email(self):
		link = reverse('users:verification', kwargs={'email': self.user.email, 'code': self.code})
		verification_link = f'{settings.DOMAIN_NAME}{link}'
		subject = f'Подтверждение учетной записи для {self.user.username}'
		message = 'Для подтверждение учетной записи для {} перейдите по ссылке: {}'.format(self.user.email,
																						   verification_link)
		send_mail(
			subject=subject,
			message=message,
			from_email=settings.EMAIL_HOST_USER,
			recipient_list=[self.user.email],
			fail_silently=False,
		)

	def is_expired(self):
		return True if now() >= self.expiration else False

Shop/users/forms.py
import uuid
from datetime import timedelta

from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm)
from django.utils.timezone import now

from users.models.comments.models import Comment
from users.models.users.models import User
from users.models.usersemailverifications.models import EmailVerification
from users.tasks import send_email_verification


class CommentForm(forms.ModelForm):
	text = forms.CharField(widget=forms.TextInput(attrs={'class': 'input-box'}))

	class Meta:
		model = Comment
		fields = ['text']


class UserLoginForm(AuthenticationForm):
	username = forms.CharField(widget=forms.TextInput(attrs={
		'type': "text",
		'placeholder': "Введите email"
	}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={
		'type': "password",
		'placeholder': "Введите пароль"
	}))

	class Meta:
		model = User
		fields = ("username", "password")


class UserRegisterForm(UserCreationForm):
	username = forms.CharField(widget=forms.TextInput(attrs={
		'type': "text",
		'placeholder': "Введите логин"
	}))
	phone = forms.CharField(widget=forms.TextInput(attrs={
		'type': "text",
		'placeholder': "Введите номер телефона"
	}))
	email = forms.CharField(widget=forms.TextInput(attrs={
		'type': "text",
		'placeholder': "Введите email"
	}))
	password2 = forms.CharField(widget=forms.TextInput(attrs={
		'type': "password",
		'placeholder': "Повторите пароль"
	}))
	password1 = forms.CharField(widget=forms.TextInput(attrs={
		'type': "password",
		'placeholder': "Введите пароль"
	}))

	class Meta:
		model = User
		fields = ('username', 'phone', 'password1', 'password2', 'email')

	def save(self, commit=True):
		user = super(UserRegisterForm, self).save(commit=True)
		send_email_verification.delay(user.id)
		return user


class UserProfileForm(UserChangeForm):
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'input-box'}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'input-box'}))
	image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'input-box'}))
	username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input-box', 'readonly': True}))
	email = forms.CharField(widget=forms.TextInput(attrs={'class': 'input-box', 'readonly': True}))
	phone = forms.CharField(widget=forms.TextInput(attrs={'class': 'input-box'}))

	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'image', 'username', 'email', 'phone', 'is_verified_email')

Shop/users/views.py
from django.contrib.auth.views import LoginView
from django.shortcuts import HttpResponseRedirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView

from common.views import TitleMixin
from users.forms import UserLoginForm, UserProfileForm, UserRegisterForm
from users.models.users.models import User
from users.models.usersemailverifications.models import EmailVerification
from users.services.emailverifaction import EmailVerifactionServices


# Create your views here.

class UserLoginView(TitleMixin, LoginView):
	form_class = UserLoginForm
	template_name = 'users/login.html'
	title = "Авторизация"


class UserRegistrationView(TitleMixin, CreateView):
	model = User
	form_class = UserRegisterForm
	template_name = 'users/register.html'
	success_url = reverse_lazy('users:truereg')
	title = "Регистрация"


class UserProfileView(TitleMixin, UpdateView):
	model = User
	form_class = UserProfileForm
	template_name = 'users/profile.html'
	title = "Личный кабинет"

	def get_success_url(self):
		return reverse_lazy('users:profile', args=(self.object.id,))


class EmailVerifactionView(TitleMixin, TemplateView):
	title = "Подтверждение электронной почты"
	template_name = "users/user_verification.html"

	def get(self, request, *args, **kwargs):
		code = kwargs['code']
		outcome = EmailVerifactionServices.execute({'code': code})
		if outcome['user'].is_verified_email:
			return super(EmailVerifactionView, self).get(request, *args, **kwargs)
		else:
			return HttpResponseRedirect(reverse('index'))


class SuccessfulRegistrationView(TitleMixin, TemplateView):
	template_name = "users/trueregister.html"
	title = 'Регистрация'

Shop/users/templates/users/login.html
{% extends 'products/base.html' %}
{% load socialaccount %}
{% load static %}
{% block content %}
<link rel='stylesheet' href='{% static "products/css/style.css" %}'>
<div class="container">
    <input type="checkbox" id="check">
    <div class="login form">
        <header style="color: #16194f">Авторизация</header>
        {% if form.non_field_errors %}
        {{ form.non_field_errors }}
        {% endif %}
        <form action="{% url 'users:login'%}" method="post">
            {% csrf_token %}
            <label for="{{ form.username.if_for_label }}">
                {{ form.username }}</label>
            <label for="{{ form.password.if_for_label }}">
                {{ form.password }}</label>
            <a href="#" style="color: #16194f">Забыли пароль?</a>
            <button>Войти</button>
        </form>
        <div class="signup">
        <span class="signup">У вас нет аккаунта?
         <a style="color: #16194f" href="{% url 'users:register' %}">Зарегистрироваться</a>
        </span>
        </div>
        Войти через:
        <div class="icons">
            <div class="icon ghb">
                <a href="{% provider_login_url 'github' %}"> <i class='bx bxl-github'></i></a>
            </div>

        </div>
    </div>
</div>
{% endblock %}

Shop/users/templates/users/profile.html
{% extends 'products/base.html' %}
{% load static %}
{% block content %}
<link rel='stylesheet' href='{% static "products/css/stylesprofile.css" %}'>
<div class="container">
    <div class="title">Личный кабинет</div>
    {% if request.user.id == user.id %}
    <div class="content">
        <form action='{% url "users:profile" user.id %} method="post"'>
            {% csrf_token %}
            <div class="user-details">
                <div class="input-box">
                    <span class="details">Имя</span>
                    <label type="text" for="{{ form.first_name.id_for_label }}"></label>
                    {{ form.first_name }}
                </div>
                <div class="input-box">
                    <span class="details">Фамилия</span>
                    <label type="text" for="{{ form.last_name.id_for_label }}"></label>
                    {{ form.last_name }}
                </div>
                <div class="input-box">
                    <span class="details">Email</span>
                    <label type="text" for="{{ form.email.id_for_label }}"></label>
                    {{ form.email }}
                    {% if user.is_verified_email %}
                    <div>
                        <i style="color:green" class="gg-check-o"></i>Почта подтверждена
                    </div>
                    {% else %}
                    <div>
                        <i style="color:red" class="gg-check-o"></i>Почта не подтверждена
                    </div>
                    <a href="#">Выслать ссылку на подтверждение на вашу почту</a>
                    {% endif %}
                </div>
                <div class="input-box">
                    <span class="details">Номер телефона</span>
                    <label type="text" for="{{ form.phone.id_for_label }}"></label>
                    {{ form.phone }}
                </div>
                <div class="input-box">
                    <span class="details">Логин</span>
                    <label type="text" for="{{ form.username.id_for_label }}"></label>
                    {{ form.username }}
                </div>
            </div>
<!--            <div class="button">-->
<!--                <input type="submit" value="Сохарнить">-->
<!--            </div>-->
        </form>
        <center><a href="{% url 'order:order_list' %}">Ваши заказы</a></center>
        <a href="{% url 'users:logout' %}">Выйти</a>
    </div>
    {% else %}
    Нед доступа
    {% endif %}
</div>

{% endblock %}

Shop/users/templates/users/register.html
{% extends 'products/base.html' %}
{% load static %}
{% block content %}

<link rel='stylesheet' href='{% static "products/css/style.css" %}'>
<div class="container">
    <input type="checkbox" id="check">
    <div class="login form">
        <header>Регистрация</header>
        {% if form.errors or messages %}
        {% if messages %}
        {% for mes in messages %}
        {{ mes }}
        {% endfor %}
        {% else %}
        {{ form.errors }}
        {% endif %}
        {% endif %}
        <form action="{% url 'users:register'%}" method="post">
            {% csrf_token %}
            <label for="{{ form.username.if_for_label }}">
                {{ form.username }}</label>
            <label for="{{ form.phone.if_for_label }}">
                {{ form.phone }}</label>
            <label for="{{ form.email.if_for_label }}">
                {{ form.email }}</label>
            <label for="{{ form.password.if_for_label }}">
                {{ form.password1 }}</label>
            <label for="{{ form.password1.if_for_label }}">
                {{ form.password2 }}</label>
            <button>Зарегестрироваться</button>
        </form>
        <div class="signup">
        <span class="signup">У вас есть аккаунт?
         <a style="color: #16194f" href="{% url 'users:login' %}">Войти</a>
        </span>
        </div>

    </div>
</div>
{% endblock %}

Shop/users/templates/users/trueregister.html
{% extends "products/base.html" %}
{% load static %}
{% block content %}
<link rel='stylesheet' href='{% static "products/css/style.css" %}'>
<div class="container">
    <input type="checkbox" id="check">
    <div class="login form">
        <header>Регистрация</header>
        <h3>Теперь вам необходимо подтвердить свой email. Перейдите по ссылке в письме на вашей почте</h3>
    </div>
</div>
{% endblock %}

Shop/users/templates/users/user_verification.html
{% load static %}
<link rel='stylesheet' href='{% static "products/css/style.css" %}'>
<div class="container">
    <input type="checkbox" id="check">
    <div class="login form">
        <header>Регистрация</header>
        <h3>Поздравляем, вы успешно зарегистрировались!</h3>
        <div class="signup">
            <a style="color: #16194f" href="{% url 'users:login' %}">Перейти на авторизацию</a>
        </div>
    </div>
</div>