Shop/Shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

from orders.views import stripe_webhook_view

urlpatterns = [
				  path('admin/', admin.site.urls),
				  path('', include("products.urls")),
				  path('user/', include("users.urls", namespace='users')),
				  path('order/', include("orders.urls", namespace='order')),
				  path('accounts/', include('allauth.urls')),
				  path('webhook/', stripe_webhook_view, name='stripe_webhook_view'),
				  path('api/', include("api.urls", namespace='api')),
				  path('api-token-auth/', views.obtain_auth_token),
			  ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/api/urls.py
from django.urls import include, path
from rest_framework import routers

from .views import BasketModelViewSet, ProductModelViewSet

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'products',ProductModelViewSet)
router.register(r'baskets',BasketModelViewSet)

urlpatterns = [
	path('', include(router.urls)),
]

Shop/orders/urls.py
from django.urls import path

from .views import *

app_name = 'orders'
urlpatterns = [path('create/', OrderCreateView.as_view(), name='create'),
			   path('success/', SuccessTemplateView.as_view(), name='success'),
			   path('cancel/', CancelTemplateView.as_view(), name='cancel'),
			   path('', OrderListView.as_view(), name='order_list'),
			   path('order/<int:pk>', OrderDetailView.as_view(), name='order_info'),
			   ]

Shop/products/urls.py
from django.urls import path

from products.views.basket.views import (BasketAddView, BasketReduceView,
                                         BasketRemoveView, BasketView)
from products.views.comment_and_serch.views import (ProductCommentView,
                                                    ProductSerchView)
from products.views.products.views import ProductsListView, ShowProdView

urlpatterns = [
	path('', ProductsListView.as_view(), name='index'),
	path('subcategory/<int:subcategory_id>/', ProductsListView.as_view(), name='categ'),
	path('products/<int:pk>/', ShowProdView.as_view(), name='products'),
	path('basket/', BasketView.as_view(), name='basket'),
	path('basket/add/<int:product_id>', BasketAddView.as_view(), name='basket_add'),
	path('basket/reduce/<int:product_id>', BasketReduceView.as_view(), name='basket_reduce'),
	path('basket/remove/<int:basket_id>', BasketRemoveView.as_view(), name='basket_remove'),
	path('comment/<int:pk>/', ProductCommentView.as_view(), name='comment'),
	path("search/", ProductSerchView.as_view(), name='search'),
]

Shop/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import *

app_name = 'users'
urlpatterns = [
	path('login/', UserLoginView.as_view(), name='login'),
	path('register/', UserRegistrationView.as_view(), name='register'),
	path('profile/<int:pk>/', UserProfileView.as_view(), name='profile'),
	path('logout/', LogoutView.as_view(), name='logout'),
	path('truereg/', SuccessfulRegistrationView.as_view(), name='truereg'),
	path('verify/<str:email>/<uuid:code>/', EmailVerifactionView.as_view(), name='verification'),
]

Shop/products/models/basemodel/models.py
from django.db import models


class BaseModel(models.Model):
	created_at = models.DateField(null=True, auto_now_add=True, verbose_name='Date of create')
	updated_at = models.DateField(auto_now=True, verbose_name='Date of update')

	class Meta:
		abstract = True
		app_label = 'shop'
		verbose_name_plural = 'Base model'

Shop/products/models/basket/models.py
from django.db import models

from products.models.basemodel.models import BaseModel
from products.models.product.models import Product
from users.models.users.models import User


class BasketQuerySet(models.QuerySet):
	def total_sum(self):
		return sum(basket.sum() for basket in self)

	def total_quantity(self):
		return sum(basket.quantity for basket in self)

	def stripe_products(self):
		line_items = []
		for basket in self:
			item = {
				'price': basket.product.stripe_product_price_id,
				'quantity': basket.quantity,
			}
			line_items.append(item)
		return line_items


class Basket(models.Model):
	user = models.ForeignKey(to=User, on_delete=models.CASCADE)
	product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
	quantity = models.PositiveIntegerField(default=0)

	objects = BasketQuerySet.as_manager()

	def __str__(self):
		return f'Корзина'

	def sum(self):
		return self.product.price * self.quantity

	def de_json(self):
		basket_item = {
			'product_name':self.product.name,
			'quantity':self.quantity,
			'price': float(self.product.price),
			'sum': float(self.sum()),
		}
		return basket_item

Shop/products/models/category/models.py
from django.db import models

from products.models.basemodel.models import BaseModel


class ProductCategory(BaseModel):
	"""Category model"""
	name = models.CharField(max_length=128, unique=True)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = "Категория"
		verbose_name_plural = "Категории"

Shop/products/models/product/models.py
import stripe
from django.conf import settings
from django.db import models

from products.models.basemodel.models import BaseModel
from products.models.subcategory.models import ProductSubCategory

stripe.api_key = settings.STRIPE_SECRET_KEY


class Product(BaseModel):
	name = models.CharField(max_length=256, unique=True)
	decription = models.TextField()
	price = models.DecimalField(max_digits=6, decimal_places=2)
	quantity = models.PositiveIntegerField(default=0)
	image = models.ImageField(upload_to="photos/%Y/%m/%d/")
	stripe_product_price_id = models.CharField(max_length=256, null=True, blank=True)
	subcategory = models.ForeignKey(to=ProductSubCategory, on_delete=models.CASCADE)

	def __str__(self):
		return self.name



	class Meta:
		verbose_name = "Продукт"
		verbose_name_plural = "Продукты"

	def create_stripe_product_price(self):
		stripe_product = stripe.Product.create(name=self.name)
		stripe_product_price = stripe.Price.create(
			product=stripe_product['id'], unit_amount=round(self.price * 100), currency='rub')
		return stripe_product_price

	def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
		if not self.stripe_product_price_id:
			stripe_prod_price = self.create_stripe_product_price()
			self.stripe_product_price_id = stripe_prod_price['id']
		super(Product,self).save(force_insert=False, force_update=False, using=None, update_fields=None)

Shop/products/models/subcategory/models.py
from django.db import models

from products.models.basemodel.models import BaseModel
from products.models.category.models import ProductCategory


class ProductSubCategory(BaseModel):
	name = models.CharField(max_length=128, unique=True)
	category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = "Подкатегория"
		verbose_name_plural = "Подкатегории"

Shop/users/models/comments/models.py
from django.db import models

from products.models.basemodel.models import BaseModel
from products.models.product.models import Product
from users.models.users.models import User


class Comment(BaseModel, models.Model):
	text = models.TextField()
	product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
	user = models.ForeignKey(to=User, on_delete=models.CASCADE)

	def __str__(self):
		return self.text

	class Meta:
		app_label = 'users'

Shop/products/views/basket/views.py
from django.shortcuts import HttpResponseRedirect
from django.views import View
from django.views.generic import ListView

from common.views import TitleMixin
from products.models.basket.models import Basket
from products.services.basket.add import BasketAddService
from products.services.basket.list import BasketListService
from products.services.basket.reduce import BasketReduceService
from products.services.basket.remove import BasketRemoveService


# Create your views here.
class BasketView(TitleMixin, ListView):
	template_name = 'products/basket.html'
	model = Basket
	title = "Корзина"

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		outcome = BasketListService.execute({'user': self.request.user})
		context['total_sum'] = outcome['total_sum']
		context['basket'] = outcome['basket']
		return context


class BasketAddView(View):
	def get(self, request, product_id, *args, **kwargs):
		outcome = BasketAddService.execute({'user': request.user, 'product': product_id})
		return HttpResponseRedirect(request.META['HTTP_REFERER'], content=outcome)


class BasketReduceView(View):
	def get(self, request, product_id, *args, **kwargs):
		outcome = BasketReduceService.execute({'user': request.user, 'product': product_id})
		return HttpResponseRedirect(request.META['HTTP_REFERER'], content=outcome)


class BasketRemoveView(View):

	def get(self, request, basket_id, *args, **kwargs):
		outcome = BasketRemoveService.execute({'basket_id': basket_id})
		return HttpResponseRedirect(request.META['HTTP_REFERER'], content=outcome)

Shop/products/views/comment_and_serch/views.py
from django.shortcuts import HttpResponseRedirect
from django.views import View
from django.views.generic import ListView

from common.views import TitleMixin
from products.models.product.models import Product
from products.services.comment.create import CommentCreateService
from products.services.serch.contextdata import ProductSerchContextDataService
from products.services.serch.queryset import ProductSerchQuerysetService
from users.forms import CommentForm

# Create your views here.


class ProductCommentView(View):

	def post(self, request, pk):
		form = CommentForm(request.POST)
		produc = Product.objects.get(id=pk)
		if form.is_valid():
			CommentCreateService.execute(
				{'product_id':produc.id,
				'user':request.user,
				'text':form.save(commit=False)})
		return HttpResponseRedirect(request.META['HTTP_REFERER'])


class ProductSerchView(TitleMixin, ListView):
	template_name = 'products/products.html'

	def get_queryset(self):
		outcome = ProductSerchQuerysetService.execute({'find':self.request.GET.get("q")})
		return outcome

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		outcome = ProductSerchContextDataService.execute({'find':f'q={self.request.GET.get("q")}&'})
		context["q"] = outcome['find_name']
		return context

	title = 'ПродуктМаркет'

Shop/products/views/products/views.py
from django.views.generic import DetailView, ListView

from common.views import TitleMixin
from products.models.product.models import Product
from products.services.product.contextdata import ProductContextDataService
from products.services.product.queryset import ProductQuerysetService

# Create your views here.

class ProductsListView(TitleMixin, ListView):
	model = Product
	template_name = 'products/products.html'
	title = 'ПродуктМакрет'

	def get_queryset(self):
		outcome = ProductQuerysetService.execute({
			'subcategory_id': self.kwargs.get('subcategory_id', 0),
		})
		return outcome

	def get_context_data(self, *, object_list=None, **kwargs):
		context = super(ProductsListView, self).get_context_data()
		outcome = ProductContextDataService.execute({})
		context['categories'] = outcome['category']
		context['subcategories'] = outcome['subcategory']
		return context


class ShowProdView(TitleMixin, DetailView):
	model = Product
	template_name = 'products/product_info.html'

Shop/products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{{title}}{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
          integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel='stylesheet' href='{% static "products/css/styles.css" %}'>

</head>
<header>
    <nav class="navigation">
        <div class="logo">
            <a href="/"><img src="{% static 'products/img/logo.jpg' %}" alt="Logo"></a>
        </div>
        <ul class="mmenuu">
            {% for category in categories %}
            <li class="nav-item">
                <a class="item">{{category.name}}</a>
                <ul class="ssubmenuu">
                    {% for subcategory in subcategories %}
                    {% if subcategory.category == category %}
                    <li class="nav-item">
                        <a href="{% url 'categ' subcategory.id %}" class="item" id="{{subcategory.name}}">{{subcategory.name}}</a>
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </li>
            {% endfor %}
        </ul>
        <div class="icons">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a href="{% url 'basket' %}">Корзина</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'users:profile' user.id %}">Личный кабинет</a>
            </li>
            {% if user.is_superuser or user.is_staff %}
            <li class="nav-item">
                <a href="{% url 'admin:index' %}">Админ панель</a>
            </li>
            {% endif %}
            {% else %}
            <li class="nav-item">
                <a href="{% url 'users:login' %}">Войти</a>
            </li>
            {% endif %}
        </div>
    </nav>
</header>
<body>

{% block content %}

{% endblock %}
</body>
</html>

Shop/products/templates/products/basket.html
{% extends 'products/base.html' %}
{% load static %}
{% block content %}
<link rel='stylesheet' href='{% static "products/css/stylebasket.css" %}'>

<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet">
<div class="container">
    <div class="content">
        {% if baskets %}
        <div class="row">
            <div class="col-md-12">
                <div class="shopping-cart">
                    <div class="cart-header d-none d-sm-none d-mb-block d-lg-block">
                        <div class="row">
                            <div class="col-md-6">
                                <h4>Товар</h4>
                            </div>
                            <div class="col-md-2">
                                <h4>Цена, Руб.</h4>
                            </div>
                            <div class="col-md-2">
                                <h4>Количество</h4>
                            </div>
                            <div class="col-md-2">
                                <h4>Удалить</h4>
                            </div>
                        </div>
                    </div>
                    {% for basket in baskets %}
                    <div class="cart-item">
                        <div class="row">
                            <div class="col-md-6 my-auto">
                                <label class="price">
                                    <img src="{{basket.product.image.url}}" style="width: 60px; height: 60px">
                                    {{basket.product.name}}
                                </label>
                            </div>
                            <div class="col-md-2 my-auto">
                                <label class="price">{{basket.sum}} </label>
                            </div>
                            <div class="col-md-2 col-7 my-auto">
                                <div class="quantity">
                                    <div class="input-group">
                                        <a href="{% url 'basket_reduce' basket.product.id %}"> <span class="btn btn1"><i class="fa fa-minus"></i></span></a>
                                        <input type="text" value="{{basket.quantity}}" class="input-quantity"/>
                                        <a href="{% url 'basket_add' basket.product.id %}"><span class="btn btn1"><i
                                                class="fa fa-plus"></i></span></a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-2 col-5 my-auto">
                                <div class="remove">
                                    <a href="{% url 'basket_remove' basket.id %}" class="btn btn-danger btn-sm">
                                        <i class="fa fa-trash"></i> Удалить
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="algncenterdiv">
                        <h4>
                            Итог - {{total_sum}} Руб.
                        </h4>
                        <div class="algncenterdiv">
                            <a href="{% url 'order:create' %}" class="btn btn-danger btn-sm">
                                Оформить заказ
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% else %}
<center><h4>Корзина пуста</h4></center>

{% endif %}
</div>
</div>

{% endblock %}

Shop/products/templates/products/product_info.html
{% extends "products/base.html" %}
{% block title %} {{product.name}} {% endblock %}
{% block content %}
{% load static %}
<style>
    .container {   width: 75%;
  border: 1px solid #ccc;
  background-color: #fff;
  border-radius: 5px; /* скругление углов блока */
  padding: 25px; /* внутренние поля */
  margin: 22px auto; /* внешние отступы */
}
 .container img {
  float: left; /* обтекание слева */
  margin-right: 20px; /* пространство между аватаркой и абзацем */
  border-radius: 50%; /* скругляет аватарку */
  width: 65px;
}

.container span {
  font-size: 18px;
  margin-right: 15px;
}
 @media (max-width: 450px) {
  .container {
    text-align: center;
  }
  .container img {
    margin: auto;
    float: none;
    display: block;
  }
}
textarea {
    resize: none;
    line-height: 1.5em;
    font-family: 'Roboto';
    font-size: 25pt;
}
}


</style>
<div class="header-content">
    <div class="left-header">
        <h1 class="h-main">
            {{product.name}}
        </h1>

        <p>
            {{product.decription}}
        </p>
        <h2>{{product.price}}Р</h2>
        <a href="{% url 'basket_add' product.id %}" class="btn">Добавить в корзину</a>
    </div>
    <div class="right-header">
        <img src="{{product.image.url}}" alt="" style="width: 100%;">
    </div>
</div>
<section class="section-contact u-pad-3">
    <div class="contact-info">
        <h2>
            Оставить отзыв о товаре
        </h2>
        <form action="{% url 'comment' product.id %}" method="post" class="mt-4">
            {% csrf_token %}
            <div class="form-group editContent">
                <!--                <label for="contactcomment" class="editContent">-->
                <!--                    Ваш комментарий *-->
                <!--                </label>-->
                <textarea cols="55" rows="5" name="text" style="width: 993px; height: 100px;"></textarea>
            </div>
            <button type="submit"
                    class="mt-3 btn btn-success btn-block py-3">
                Отправить
            </button>
        </form>
    </div>
    {% for review in product.comment_set.all %}
    <div class="container">
        <img src="{% if user.img %} {{ user.img.url }} {% else %} {% static 'defolt_photo/pngwing.com.png' %} {% endif %}"
             alt="avatar">
        <p><span>{{ review.user }}</span>{{ review.created_at }}</p>
        <p>{{ review.text }}</p>
    </div>
    {% endfor %}

</section>
{% endblock %}

Shop/products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}

<main class="main-content">

    <section class="section-about u-pad-3">
        <div class="main-title">
            <h2>Интернет магазин <span>ПродуктМаркет.</span></h2>
        </div>
        <center>
            <div class="search-wrapper">
                <form action="{% url 'search' %}" method="get" class="d-flex editContent">
                    <input type="search" placeholder="Введите название продукта" name="q" class="search-box" required="">
                </form>
            </div>
        </center>
    </section>
    <section class="section-portfolio u-pad-3">
        <div class="main-title">
            <p>Самые популярные товары</p>
        </div>
        <div class="portfolios">
            {% for product in object_list %}
            <h1 style="color: #16194f">{{product.name}}.<p style="color: #f44e77">{{product.price}} Р.</p><br><a
                    href="{% url 'products' product.id %}">Просмотреть товар</a></br></h1>
            <div class="portfolio">
                <div class="image">
                    <img src="{{product.image.url}}">
                </div>
            </div>
            {% endfor %}
        </div>
    </section>
</main>
{% endblock %}